name: ecommerce ci and cd
on:
  push:
    branches: [main]
jobs:
  unit-test:
    runs-on: ubuntu-latest
    services:
      mysql-services:
        image: mysql:5.7.31
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DB_PASSWORD }}
          MYSQL_DATABASE: db_test
          ports:
            - 33306:3306
          options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: php-setup
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3.21'
          extensions: bcmath, ctype, fileinfo, json, mbstring, openssl, pdo, tokenizer, xml
          tools: composer:v2, phpunit
      - name: laravel-setup
        run: |
          cp .env.ci .env
          composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
          php artisan key:generate
          chmod -R 777 storage bootstrap/cache
      - name: migrate-database
        env:
          DB_CONNECTION: mysql
          DB_DATABASE: db_test
          DB_PORT: 33306
          DB_USER: root
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: php artisan migrate
      - name: run-test
        run: php artisan test
